name: 'Wait for GitHub Job'
description: 'A GitHub Action to wait for a specific job to complete'
inputs:
  token:
    description: 'GitHub token'
    required: true
  job_name:
    description: 'Name of the job to wait for'
    required: true
  minutes:
    description: 'Max wait time in minutes'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/entrypoint.sh'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.job_name }}
    - ${{ inputs.minutes }}
